name: Build and Release WebApp

on: push

jobs:
  hosting:
    name: Deploy Flutter WebApp to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      # Enable Flutter Web, Get Dependencies, and Build Web
      - name: Build Flutter WebApp
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}