name: Build and Release WebApp

on: push

jobs:
  hosting:
    name: Deploy Flutter WebApp to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Build Flutter WebApp
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYPORTFOLIO_9A480 }}'
          channelId: live
          projectId: myportfolio-9a480